//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PushDataVSMVCTutorial.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("k7S55zjm8czFd5RXEjkow")]
        public string TwitterConsumerKey {
            get {
                return ((string)(this["TwitterConsumerKey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4keDpedS0PwdzI9x0Es19yR6lvBBW5dmTJO2hPduJX0")]
        public string TwitterConsumerSecret {
            get {
                return ((string)(this["TwitterConsumerSecret"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("275166896-57ZPPPiZdoUfVO5RlUiyzKsVEEh5a6HiWR2ayItY")]
        public string TwitterToken {
            get {
                return ((string)(this["TwitterToken"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8GIlFqmqqdpuRUcMTYYkGYzmWoeM6geODHjCLUQxgow8E")]
        public string TwitterTokenSecret {
            get {
                return ((string)(this["TwitterTokenSecret"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.twitter.com/1.1/statuses/user_timeline.json?include_rts=true&geo_enab" +
            "led=true&count=1&screen_name=")]
        public string TwitterGetUserTimeline {
            get {
                return ((string)(this["TwitterGetUserTimeline"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.twitter.com/1.1/search/tweets.json?q=programming&coordinates!=null&re" +
            "sult_type=recent&count=1&include_entities=true")]
        public string TwitterSearchCriteria {
            get {
                return ((string)(this["TwitterSearchCriteria"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.twitter.com/1.1/statuses/show.json?id=")]
        public string TwitterTweetCoordinates {
            get {
                return ((string)(this["TwitterTweetCoordinates"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://maps.googleapis.com/maps/api/staticmap?center=")]
        public string StaticGoogleMapApi {
            get {
                return ((string)(this["StaticGoogleMapApi"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://maps.googleapis.com/maps/api/staticmap?center=South Africa,WA&zoom=1&size=" +
            "800x800&sensor=false")]
        public string DefaultStaticGoogleMapApi {
            get {
                return ((string)(this["DefaultStaticGoogleMapApi"]));
            }
        }
    }
}
